Parameters:
  MySSHKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Provide the KeyName which is created

  ImageID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: This will fetch the latest ami id 

  InstanceType:
    Type: String
    Default: t2.nano
    AllowedValues:
      - "t2.nano"
      - "t2.micro"
      - "t2.small"
    ConstraintDescription: Allowed valid EC2 Instance Type  

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageID
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref MySecurityGroup
      KeyName: !Ref MySSHKeyName 

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This security group enable ssh for the instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0                  
