Parameters:
  MySSHKey:
    Description: This take the keyname from the user
    Type: AWS::EC2::KeyPair::KeyName

  MyImageID:
    Description: Picks the latest amazon2 linux
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2  

  MyInstanceType:
    Description: Provide the valid aws Instance Type
    Type: String
    Default: t2.nano
    AllowedValues:
      - "t2.nano"
      - "t2.micro"
      - "t2.small"
    ConstraintDescription: Please enter valid aws instance

  MySecurityPort:
    Description: set the ports for the instance
    Type: Number
    MinValue: 10
    MaxValue: 100  

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref MyImageID
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MySSHKey
      SecurityGroups:
        - !Ref MySecurityGroup
  
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This is security group enables the SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          ToPort: !Ref MySecurityPort
          FromPort: !Ref MySecurityPort
          CidrIp: 0.0.0.0/0

  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2Instance        
        

    
      