Parameters:
  Mysshkeys:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Provide the available keyname

  MyImageID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Select the availiability zone

  EnvType:
    Type: String
    Default: Dev
    AllowedValues:
      - "Dev"
      - "UAT"
      - "Prod"
    Description: Select the env type

Mappings:
  EnvToInstance:
    Dev:
      InstanceType: t2.small
    UAT:
      InstanceType: t2.micro
    Prod:
      InstanceType: t2.small

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref MyImageID
      AvailabilityZone: !Ref AvailabilityZone
      InstanceType: !FindInMap [EnvToInstance, !Ref EnvType, InstanceType] 
      SecurityGroups:
        - !Ref MySecurityGroup
      KeyName: !Ref Mysshkeys 

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This is security group to enable ssh      
      SecurityGroupIngress:
        - IpProtocol: tcp
          ToPort: 22
          FromPort: 22
          CidrIp: 0.0.0.0/0
  
  MyStorage:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: ap-south-1a
      Size: 1
      VolumeType: standard

  AttachStorage:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      Device: /dev/sdh
      InstanceId: !Ref MyEC2Instance
      VolumeId: !Ref MyStorage

  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2Instance