Resources:
  MyVPCCF:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.72.0.0/16

  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref  MyVPCCF
      CidrBlock: 10.72.16.0/20

  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPCCF
    
  AccociateSubnetRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MySubnet
      RouteTableId: !Ref MyRouteTable