Parameters:
  myInstanceID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  myAvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name

  EnvType:
    Type: String
    Description: Select the enviroment type
    Default: Dev
    AllowedValues:
      - "Dev"
      - "UAT"
      - "Prod"
    ConstraintDescription: Must specify the environment

  keyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the keyname  

Conditions:
  prodresource: !Equals [ !Ref EnvType, Prod ]
  uatresource: !Equals [ !Ref EnvType, UAT ]
  CreateProdResource: !Or [ !Equals [ Prod, !Ref EnvType ], Condition: uatresource ]

Resources:
  myec2instances:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      AvailabilityZone: !Ref myAvailabilityZone
      ImageId: !Ref myInstanceID
      SecurityGroups:
        - !Ref mysecuritygroup
      KeyName: !Ref keyName  

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Condition: CreateProdResource
    Properties:
      Device: /dev/sdh
      InstanceId: !Ref myec2instances 
      VolumeId: !Ref myvolume

  myvolume:
    Type: AWS::EC2::Volume
    Condition: CreateProdResource 
    Properties:
      Size: 1
      AvailabilityZone: !Ref myAvailabilityZone

  mysecuritygroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: For SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0